export const columnDefs = [
  { key: "invoice", label: "Invoice #" },
  { key: "jobId", label: "Job ID" },
  { key: "name", label: "Customer Name" },
  { key: "phones", label: "Phones", sortable: false, width: 160 },
  { key: "address", label: "Address" },
  { key: "date", label: "Date" },
  { key: "type", label: "Job Type" },
  { key: "tech", label: "Collected By" },
  { key: "total", label: "Total Amount" },
  { key: "cashTotal", label: "Cash" },
  { key: "creditTotal", label: "Credit" },
  { key: "checkTotal", label: "Check" },
  { key: "zelleTotal", label: "Zelle" },
  { key: "techParts", label: "Tech Parts" },
  { key: "leadParts", label: "Lead Parts" },
  { key: "compParts", label: "Company Parts" },
  { key: "partsAmt", label: "Parts Amount" },
  { key: "cc", label: "CC Fee $" },
  { key: "addFee", label: "Additional Fee $" },
  { key: "adjusted", label: "Adjusted Total" },
  { key: "tech%", label: "Tech %" },
  { key: "techProfit", label: "Tech Profit" },
  { key: "lead%", label: "Lead %" },
  { key: "leadProfit", label: "Lead Profit" },
  { key: "comp%", label: "Company %" },
  { key: "compProfit", label: "Company Profit" },
  { key: "techBal", label: "Tech Balance" },
  { key: "leadBal", label: "Lead Balance" },
  { key: "compBal", label: "Company Balance" },
  { key: "check", label: "Financial Check" },
];