export const columnDefs = [
  { key: "invoice", label: "Invoice #" },
  { key: "jobId", label: "Job ID" },
  { key: "customerName", label: "Customer" },
  { key: "address", label: "Address" },
  { key: "date", label: "Date" },
  { key: "jobType", label: "Job Type" },
  { key: "collectedBy", label: "Collected By" },
  { key: "totalAmount", label: "Total Amount" },

  // ✅ NEW PAYMENT COLUMNS (correct key syntax)
  { key: "cashTotal", label: "Cash", numeric: true, visible: true },
  { key: "creditTotal", label: "Credit", numeric: true, visible: true },
  { key: "checkTotal", label: "Check", numeric: true, visible: true },
  { key: "zelleTotal", label: "Zelle", numeric: true, visible: true },

  { key: "techParts", label: "Tech Parts" },
  { key: "leadParts", label: "Lead Parts" },
  { key: "companyParts", label: "Company Parts" },
  { key: "totalParts", label: "Parts Amount" },
  { key: "ccFee", label: "CC Fee $" },
  { key: "addFee", label: "Additional Fee $" },
  { key: "adjustedTotal", label: "Adjusted Total" },
  { key: "techPercent", label: "Tech %" },
  { key: "techProfit", label: "Tech Profit" },
  { key: "leadPercent", label: "Lead %" },
  { key: "leadProfit", label: "Lead Profit" },
  { key: "companyPercent", label: "Company %" },
  { key: "companyProfit", label: "Company Profit" },
  { key: "techBalance", label: "Tech Balance" },
  { key: "leadBalance", label: "Lead Balance" },
  { key: "companyBalance", label: "Company Balance" },
  { key: "sumCheck", label: "Financial Check" },
];