ALTER TABLE "User" ADD COLUMN "canSeeLeadSource" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canSeeTechnicianField" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canChangeJobType" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canEditCustomerInfo" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canRefreshExtension" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canDeleteJob" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canDuplicateJob" BOOLEAN NOT NULL DEFAULT true;
