ALTER TABLE "User" ADD COLUMN "canEditCustomerName" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canEditCustomerAddress" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canSeeDashboard" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canUseChat" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "canSeeSearch" BOOLEAN NOT NULL DEFAULT true;
